CC = cl
CFLAGS = /O2 /sdl /Isrc /D_CRT_SECURE_NO_WARNINGS

ASCIGRAM_SRC = \
	src\version.obj

all: ascigram.exe

ascigram.exe: bin\ascigram.obj bin\option.obj $(ASCIGRAM_SRC)
	$(CC) $** /link $(LDFLAGS) /out:$@

# Housekeeping

clean:
	del $(ASCIGRAM_SRC)
	del ascigram.exe


# Generic object compilations

.c.obj:
	$(CC) $(CFLAGS) /c $< /Fo$@


# Testing

test: ascigram.exe
	python test\runner.py
